judge:
  name: "Justice_Jules"
  role: "The Supreme Judge"
  model: "llama3.1" 
  prompt_file: "judge.txt"
agents:
  - name: "Turbo_Tim"
    role: "Mathematician"
    model: "llama3.1"
    prompt_file: "mathematician.txt" 

  - name: "Hacker_Hank"
    role: "Speed Hacker"
    model: "llama3.1"
    prompt_file: "hacker.txt"

  - name: "Pythonic_Pete"
    role: "Clean Coder"
    model: "mistral"
    prompt_file: "clean_coder.txt"

  - name: "Minimal_Max"
    role: "Memory Optimizer"
    model: "llama3.1"
    prompt_file: "minimalist.txt"