judge:
  name: "Supreme_AI"
  role: "The Arbiter"
  model: "gpt-4o" 
  prompt_file: "judge.txt"

agents:
  - name: "Turbo_Tim"
    role: "Speed Optimizer"
    model: "llama-3.1" 
    prompt_file: "mathematician.txt"

  - name: "Hacker_Hank"
    role: "Speed Hacker"
    model: "llama-3.1"
    prompt_file: "hacker.txt"

  - name: "Pythonic_Pete"
    role: "Clean Coder"
    model: "Mistral" 
    prompt_file: "clean_coder.txt"

  - name: "Minimal_Max"
    role: "Memory Optimizer"
    model: "llama-3.1" 
    prompt_file: "minimalist.txt"